services:
  visualizator:
    container_name: visualizator-dev-container
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    environment:
      - BACKEND_BASE_URL=${BACKEND_BASE_URL}
      - USE_MOCK_TILES=${USE_MOCK_TILES}
      - TILE_FORMAT=${TILE_FORMAT}
      - APP_HOST_PORT=${APP_HOST_PORT}
      - DOCS_URL=${DOCS_URL}
    volumes:
      - .:/app
    restart: unless-stopped

  docs:
    container_name: docs-dev-container
    build:
      context: ./docs
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=development
