services:
  docs-service:
    container_name: docs-service-dev-container
    build:
      context: ./docs-service
      dockerfile: Dockerfile.dev
    ports:
      - "${DOCS_HOST_PORT}:3000"
    volumes:
      - ./docs-service:/app
    environment:
      - NODE_ENV=development
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://127.0.0.1:3000 || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
      start_interval: 1s

  visualizer:
    container_name: visualizer-dev-container
    depends_on:
      docs-service:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    environment:
      - BACKEND_BASE_URL=${BACKEND_BASE_URL}
      - TILE_FORMAT=${TILE_FORMAT}
      - APP_HOST_PORT=${APP_HOST_PORT}
      - DOCS_URL=${DOCS_URL}
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://127.0.0.1:4200 || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
      start_interval: 1s
