/**
 * Configuración para producción
 */
export const environment = {
  production: true,
  backend: {
    baseUrl: $ENV.BACKEND_BASE_URL,
    useMockTiles: $ENV.USE_MOCK_TILES,
  },
  tiles: {
    format: $ENV.TILE_FORMAT,
  },
  ui: {
    disabledLayers: [
      'abi-ch2',
      'radar',
      // IGN WMS layers - disabled for production
      'ign-limite-area-protegida',
      'ign-limite-zona-frontera',
      'ign-limite-espacios-maritimos',
      'ign-hitos-internacionales',
      'ign-hitos-interprovinciales',
      'ign-gobierno-local-punto',
      'ign-gobierno-local-poligono',
      'ign-circulo-polar',
      'ign-ecuador',
      'ign-tropico',
      'ign-200-millas-antartico',
      'ign-mar-territorial',
      'ign-plataforma-continental',
      'ign-zona-contigua',
      'ign-zona-economica-exclusiva',
      'ign-red-gps-ramsac',
      'ign-red-nivelacion-alta-precision',
      'ign-red-nivelacion-precision',
      'ign-red-nivelacion-topografica',
      'ign-red-posgar07',
      'ign-red-densificacion-posgar07',
      'ign-red-pasma',
      'ign-red-provincial',
      'ign-red-gravimetrica-bacara',
      'ign-red-gravimetrica-primer-orden',
      'ign-red-gravimetrica-segundo-orden',
      'ign-red-gravimetrica-tercer-orden',
      'ign-red-gravimetrica-igsn71',
      'ign-red-gravimetrica-raga',
      'ign-red-ramsac-ntrip',
      'ign-area-desarrollo-fronteras',
      'ign-area-protegida',
      'ign-departamento',
      'ign-pais',
      'ign-provincia',
      'ign-zona-frontera-area',
    ],
  },
};
